Imported from conserver-7.2.4.tar.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -840,16 +840,20 @@ Optional Packages:
   --with-port=PORT        Specify port number [conserver]
   --with-base=PORT        Base port for secondary channel [0]
   --with-master=MASTER    Specify master server hostname [console]
-  --with-cffile=CFFILE    Specify config filename [conserver.cf]
-  --with-pwdfile=PWDFILE  Specify password filename [conserver.passwd]
+  --with-cffile=CFFILE    Specify config filename
+                          [SYSCONFDIR/conserver.cf]
+  --with-pwdfile=PWDFILE  Specify password filename
+                          [SYSCONFDIR/conserver.passwd]
   --with-logfile=LOGFILE  Specify log filename [/var/log/conserver]
   --with-pidfile=PIDFILE  Specify PID filepath [/var/run/conserver.pid]
   --with-maxmemb=MAXMEMB  Specify maximum consoles per process [16]
   --with-timeout=TIMEOUT  Specify connect() timeout in seconds [10]
   --with-libwrap[=PATH]
                           Compile in libwrap (tcp_wrappers) support
+  --with-openssl[=PATH]
+                          Compile in OpenSSL support
   --with-regex            Use regular expressions in conserver.passwd
-  --with-pam              enable PAM support
+  --with-pam              Enable PAM support
 
 Some influential environment variables:
   CC          C compiler command
@@ -1363,15 +1367,24 @@ echo $ECHO_N "checking for configuration filename... $ECHO_C" >&6
 if test "${with_cffile+set}" = set; then
   withval="$with_cffile"
   if test "$withval" != yes; then
-		cat >>confdefs.h <<_ACEOF
+		if expr "x$withval" : "x/" > /dev/null 2>&1; then
+			cat >>confdefs.h <<_ACEOF
 #define CONFIGFILE "$withval"
 _ACEOF
 
-		echo "$as_me:$LINENO: result: '$sysconfdir/$withval'" >&5
+			echo "$as_me:$LINENO: result: '$withval'" >&5
+echo "${ECHO_T}'$withval'" >&6
+		else
+			cat >>confdefs.h <<_ACEOF
+#define CONFIGFILE SYSCONFDIR "/$withval"
+_ACEOF
+
+			echo "$as_me:$LINENO: result: '$sysconfdir/$withval'" >&5
 echo "${ECHO_T}'$sysconfdir/$withval'" >&6
+		fi
 	else
 		cat >>confdefs.h <<_ACEOF
-#define CONFIGFILE "conserver.cf"
+#define CONFIGFILE SYSCONFDIR "/conserver.cf"
 _ACEOF
 
 		echo "$as_me:$LINENO: result: '$sysconfdir/conserver.cf'" >&5
@@ -1379,7 +1392,7 @@ echo "${ECHO_T}'$sysconfdir/conserver.cf'" >&6
 	fi
 else
   cat >>confdefs.h <<_ACEOF
-#define CONFIGFILE "conserver.cf"
+#define CONFIGFILE SYSCONFDIR "/conserver.cf"
 _ACEOF
 
 	echo "$as_me:$LINENO: result: '$sysconfdir/conserver.cf'" >&5
@@ -1393,15 +1406,24 @@ echo $ECHO_N "checking for password filename... $ECHO_C" >&6
 if test "${with_pwdfile+set}" = set; then
   withval="$with_pwdfile"
   if test "$withval" != yes; then
-		cat >>confdefs.h <<_ACEOF
+		if expr "x$withval" : "x/" > /dev/null 2>&1; then
+			cat >>confdefs.h <<_ACEOF
 #define PASSWDFILE "$withval"
 _ACEOF
 
-		echo "$as_me:$LINENO: result: '$sysconfdir/$withval'" >&5
+			echo "$as_me:$LINENO: result: '$withval'" >&5
+echo "${ECHO_T}'$withval'" >&6
+		else
+			cat >>confdefs.h <<_ACEOF
+#define PASSWDFILE SYSCONFDIR "/$withval"
+_ACEOF
+
+			echo "$as_me:$LINENO: result: '$sysconfdir/$withval'" >&5
 echo "${ECHO_T}'$sysconfdir/$withval'" >&6
+		fi
 	else
 		cat >>confdefs.h <<_ACEOF
-#define PASSWDFILE "conserver.passwd"
+#define PASSWDFILE SYSCONFDIR "/conserver.passwd"
 _ACEOF
 
 		echo "$as_me:$LINENO: result: '$sysconfdir/conserver.passwd'" >&5
@@ -1409,7 +1431,7 @@ echo "${ECHO_T}'$sysconfdir/conserver.passwd'" >&6
 	fi
 else
   cat >>confdefs.h <<_ACEOF
-#define PASSWDFILE "conserver.passwd"
+#define PASSWDFILE SYSCONFDIR "/conserver.passwd"
 _ACEOF
 
 	echo "$as_me:$LINENO: result: '$sysconfdir/conserver.passwd'" >&5
@@ -4476,6 +4498,7 @@ _ACEOF
 fi
 
 
+
 echo "$as_me:$LINENO: checking for library containing socket" >&5
 echo $ECHO_N "checking for library containing socket... $ECHO_C" >&6
 if test "${ac_cv_search_socket+set}" = set; then
@@ -4943,6 +4966,184 @@ fi
 	LIBS="$oLIBS"
 	CPPFLAGS="$oCPPFLAGS"
 	LDFLAGS="$oLDFLAGS"
+    fi
+
+fi;
+
+
+# Check whether --with-openssl or --without-openssl was given.
+if test "${with_openssl+set}" = set; then
+  withval="$with_openssl"
+  if test "$withval" != "no"; then
+	if test "$withval" != "yes"; then
+	    OPENSSLCPPFLAGS="-I$withval/include"
+	    OPENSSLLDFLAGS="-L$withval/lib"
+	else
+	    OPENSSLCPPFLAGS=""
+	    OPENSSLLDFLAGS=""
+	fi
+
+	oCPPFLAGS="$CPPFLAGS"
+	oLDFLAGS="$LDFLAGS"
+	oLIBS="$LIBS"
+	have_openssl=no
+
+	CPPFLAGS="$CPPFLAGS $OPENSSLCPPFLAGS"
+	LDFLAGS="$LDFLAGS $OPENSSLLDFLAGS"
+
+	if test "${ac_cv_header_openssl_ssl_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for openssl/ssl.h" >&5
+echo $ECHO_N "checking for openssl/ssl.h... $ECHO_C" >&6
+if test "${ac_cv_header_openssl_ssl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_openssl_ssl_h" >&5
+echo "${ECHO_T}$ac_cv_header_openssl_ssl_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking openssl/ssl.h usability" >&5
+echo $ECHO_N "checking openssl/ssl.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <openssl/ssl.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking openssl/ssl.h presence" >&5
+echo $ECHO_N "checking openssl/ssl.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <openssl/ssl.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: openssl/ssl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: openssl/ssl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/ssl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: openssl/ssl.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: openssl/ssl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: openssl/ssl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/ssl.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: openssl/ssl.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/ssl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: openssl/ssl.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for openssl/ssl.h" >&5
+echo $ECHO_N "checking for openssl/ssl.h... $ECHO_C" >&6
+if test "${ac_cv_header_openssl_ssl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_openssl_ssl_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_openssl_ssl_h" >&5
+echo "${ECHO_T}$ac_cv_header_openssl_ssl_h" >&6
+
+fi
+if test $ac_cv_header_openssl_ssl_h = yes; then
+  LIBS="$LIBS -lssl -lcrypto"
+	    echo "$as_me:$LINENO: checking for openssl libraries -lssl and -lcrypto" >&5
+echo $ECHO_N "checking for openssl libraries -lssl and -lcrypto... $ECHO_C" >&6
+	    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <openssl/ssl.h>
+
+int
+main ()
+{
+SSL_library_init()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENSSL 1
+_ACEOF
+
+		have_openssl=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+
+
+
+	if test $have_openssl = no; then
+	    LIBS="$oLIBS"
+	    CPPFLAGS="$oCPPFLAGS"
+	    LDFLAGS="$oLDFLAGS"
+	fi
     fi
 
 fi;
